### ISSUE TITLE
Can't execute the jar.

### ISSUE THREAD

**Issue by KoxSosen** [Technove/AirplaneLite#1]
My java version:

![image](https://user-images.githubusercontent.com/67807644/101979310-507d9f80-3c5c-11eb-8ead-aeb5e1f56da1.png)

I donwloaded the jdk8, jdk11 version also, but can't execute the jar.

![image](https://user-images.githubusercontent.com/67807644/101979336-8ae73c80-3c5c-11eb-8d3a-c9dcc97ea2d8.png)

**Comment by KoxSosen** [comment]
Update:  I was able to start the jar when executing directly from the terminal. The startup script has the same content as what I executed.

**Comment by DeadSteve51** [comment]
Yay the one issue ever is just someone who messed up with starting it up

**Comment by KoxSosen** [comment]
Yep, sorry for this one as well, my win7 file endings screwed me over.
