### ISSUE TITLE
1.17: Ice starts appearing everywhere underwater

### ISSUE THREAD

**Issue by metabrixkt** [Technove/AirplaneLite#25]
**Observed behavior**
Ice replaces water layer that is under top layer. It happens everywhere, even in desert.

**Expected behavior**
Ice replaces top water layer in cold biomes only.

**Steps to reproduce**
1. Download purpur/1.17, commit e9bf399. (it also happens on ver/1.17, commit 527a3cf)
2. Ice starts appearing everywhere. (you may need to wait few seconds after server start)

**Version**
`git-AirplanePurpur-"e9bf399" (MC: 1.17)`

**Additional info**
Bug isn't reproducible on Purpur ver/1.17 b1191, Tuinity ver/1.17 b1d612f and Paper master 9e07703.

**Screenshot**
![image](https://user-images.githubusercontent.com/64396538/123428796-a0f89100-d5df-11eb-895e-29883f47eff3.png)

**Comment by metabrixkt** [comment]
New thing I noticed:
> I can't reproduce this bug with aikar flags. On any software.
> I **can** reproduce this bug **only on airplane** with hilltty flags:
> ```
> java -server -Xms2G -Xmx2G -XX:+UseLargePages -XX:LargePageSizeInBytes=2M -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -XX:+DisableExplicitGC --illegal-access=permit -jar launcher-airplanepurpur.jar --nogui
> ```

**Comment by PaulBGD** [comment]
I'm going to close this as the Tuinity issue exists.
