### ISSUE TITLE
minecarts optimization bug

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Technove/AirplaneLite#28]
The minecarts stop and cannot be set in motion by anything, that is, they are not affected by a collision. this happens randomly and quite rarely, but on a server scale it is dozens of problems every day. the easiest way to try to reproduce it is to get off the minecarts and stop it, after a while it will be impossible to push or interact in any way except for the broke. there is also a problem of minecarts with hoppers, they also stop unloading loot.
there is no such problem on paper, this is an optimization bug

all versions

plugins: traincarts (the problem is observed even without plugins)

**Comment by PaulBGD** [comment]
Given this happens on Tuinity, please reproduce on a Tuinity server without plugins and report to them.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> Given this happens on Tuinity, please reproduce on a Tuinity server without plugins and report to them.

i use the airplane core and it is logical that I should contact you, but your core is based on tuinity and the bug is in it, so you need to make a patch for airplane

**Comment by Envel-Nikita-Gutsenkov** [comment]
if there is a bug in tuinity, then it should also be in airplane?

**Comment by metabrixkt** [comment]
> > Given this happens on Tuinity, please reproduce on a Tuinity server without plugins and report to them.
> 
> i use the airplane core and it is logical that I should contact you, but your core is based on tuinity and the bug is in it, so you need to make a patch for airplane

If the bug is caused by Tuinity, you should report it to them.


> if there is a bug in tuinity, then it should also be in airplane?

Yes, but it's still caused by Tuinity, so Tuinity should fix it, not Airplane.

**Comment by PaulBGD** [comment]
It may be logical to you, but it's not logical to me that you would presume Airplane has to fix every bug itself. I've told you what you can do to get this fixed, if you're not willing to do that then it's unlikely it'll get fixed in a reasonable timeframe.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> > > Given this happens on Tuinity, please reproduce on a Tuinity server without plugins and report to them.
> > 
> > 
> > i use the airplane core and it is logical that I should contact you, but your core is based on tuinity and the bug is in it, so you need to make a patch for airplane
> 
> If the bug is caused by Tuinity, you should report it to them.
> 
> > if there is a bug in tuinity, then it should also be in airplane?
> 
> Yes, but it's still caused by Tuinity, so Tuinity should fix it, not Airplane.

you are making a fork of the core, but you do not want to fix bugs in it and send me to third-party developers O_o

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> It may be logical to you, but it's not logical to me that you would presume Airplane has to fix every bug itself. I've told you what you can do to get this fixed, if you're not willing to do that then it's unlikely it'll get fixed in a reasonable timeframe.

I don't quite understand you

**Comment by PaulBGD** [comment]
Evidently you don't respect my team or our project, so I'm done responding to this issue.
