### ISSUE TITLE
Lava is turned into air instead of obsidian

### ISSUE THREAD

**Issue by galacticwarrior9** [Technove/AirplaneLite#29]
On the latest build of Airplane-Purpur, lava source blocks no longer turn into obsidian when water flows over them. Instead, they will be replaced by air. This was tested on a server with no plugins. 

I was unable to reproduce this with the previous build. I suspect [this commit](https://github.com/TECHNOVE/Airplane/commit/0baec0f5336cdc98ff3ec8bec3b8e0bd48ab7a6e) is responsible. 

[Here's a video](https://streamable.com/9vszyb)

`/version` output: 
```
AirplanePurpur version git-AirplanePurpur-9 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 5d9af1f on HEAD)
```

**Comment by PaulBGD** [comment]
Appreciate the report, all fixed.
