### ISSUE TITLE
(On join) server has not responded within 10 seconds

### ISSUE THREAD

**Issue by andrew121410** [Technove/AirplaneLite#32]
Ok, so airplane was working just fine for me a couple of commits back but I can't find out why this is happening now every time I join the server I get (check the log)

I went to tuinity just to see if it happens with that but no the server works just fine with tuinity latest build so this seems like a airplane issue

[latest.log](https://github.com/TECHNOVE/Airplane/files/6766886/latest.log)

**Comment by PaulBGD** [comment]
882854414217515a884634883c00e7a2e6c3f428
