### ISSUE TITLE
Projectiles fail to spawn after a certain number exist in the world

### ISSUE THREAD

**Issue by galacticwarrior9** [Technove/AirplaneLite#46]
After a certain number of projectiles exist in the world, all other attempts at spawning projectiles will fail. 

This could not be reproduced on vanilla, Paper or Tuinity, but is reproducible using Airplane 50 and Airplane-Purpur 22.

The issue is demonstrated in [this video](https://streamable.com/0kvg0d).

I have been told that the source of the problem lies in line 43 of [this patch](https://github.com/TECHNOVE/Airplane/blob/ver/1.17/patches/server/0010-Reduce-projectile-chunk-loading.patch#L43): `newX` is calculated using `z` instead of `x`.

**Comment by PaulBGD** [comment]
Wow, great catch! Who told you that?

**Comment by galacticwarrior9** [comment]
Thank you - it was one of my server's administrators.

**Comment by PaulBGD** [comment]
They're very smart! Fixed on latest.
