### ISSUE TITLE
Plugin (maybe with chinese file name) cannot work successfully.

### ISSUE THREAD

**Issue by IceBear003** [Technove/AirplaneLite#50]
It said that the description is null. 
But I even didn't add description to my plugin.yml when programming.
And I tried to add a description but it still broke down
And other functions of my plugin have worked very well.
![QQ图片20210802195525](https://user-images.githubusercontent.com/46891330/127858343-92082062-0826-4bf4-b266-84e71cac60eb.png)

**Comment by IceBear003** [comment]
my code and plugin.yml
https://i.loli.net/2021/08/02/lq3ToQ1Frfbp5j2.png
https://i.loli.net/2021/08/02/dy2hsFqJU3EL1Sv.png

sorry for my bad english. tks for watching!

**Comment by PaulBGD** [comment]
Does this plugin work on Paper or Spigot?

**Comment by IceBear003** [comment]
it works well on tuinity server

**Comment by PaulBGD** [comment]
Please send the plugin.

**Comment by IceBear003** [comment]
I change my plugin's name and it's ok now

tks
