### ISSUE TITLE
Flare profiler overrides any plugins /profile commands

### ISSUE THREAD

**Issue by viomck** [Technove/AirplaneLite#51]
An easy enough solution would be to disable Flare commands when web token is nothing... but does anyone even use the profile alias? I feel like we could pretty easily just remove any generic aliases and stick with /flare.

My vote is to just remove the /profile alias, but either solution will work. Can PR if needed.

Relevant line is https://github.com/TECHNOVE/Airplane/blob/ver/1.17/patches/server/0014-Airplane-Profiler.patch#L260

Internal ticket reference: 0413

/cc @PaulBGD

**Comment by PaulBGD** [comment]
Already fixed on 1.17, could be backported.

**Comment by viomck** [comment]
> Already fixed on 1.17, could be backported.

Which commit fixes this in 1.17?

**Comment by PaulBGD** [comment]
https://github.com/TECHNOVE/Airplane/commit/1d2c66417564f6e21471522a45233bfff5aa495f

**Comment by viomck** [comment]
I see
```diff
+        // todo lookup token (off-thread) and let users know if their token is valid
+        if (accessToken.length() > 0) {
```

& personally don't think there'd be any issue merging this line but just checking do you know of anything 1.16 -> 1.17 that would affect this or should I be good to use the same method?

**Comment by PaulBGD** [comment]
That's all it is, except if you copy the code exactly note that I accidentally did the null check wrong haha

**Comment by PaulBGD** [comment]
I'll be honest, 1.16 isn't super top priority. We'd accept a PR, but I don't think it's something I'd add right now.
