### ISSUE TITLE
Server crash after spam

### ISSUE THREAD

**Issue by ghost** [Technove/AirplaneLite#59]
crash log:
http://hastebin.com/ilowabaraj.coffeescript

server log:
http://hastebin.com/bumuwapemo.csharp

video demonstration:

https://user-images.githubusercontent.com/18630111/133021229-5e0ef5c4-e85b-4209-8ff2-9bacb64d165b.mp4

**Comment by PaulBGD** [comment]
I'll look into this.

**Comment by MennoGamed** [comment]
Would it be an option to change your Minecraft language to English? Then the error in your image is easier to read. Not sure if this matters to Paul.

**Comment by ghost** [comment]
@MennoGamed , look in the logs, there the reason for the kick is written in English, since it is TranslatableComponent message

**Comment by PaulBGD** [comment]
This appears to happen when a plugin creates a world async, which afaik is actually allowed for some reason. I think some better thread checks in paper would be a good way to fix this.

**Comment by PaulBGD** [comment]
I'm going to close this unless someone else can reproduce, as it's likely a plugin issue.
