### ISSUE TITLE
Lava Bug

### ISSUE THREAD

**Issue by Pantera07** [Technove/AirplaneLite#60]
https://drive.google.com/file/d/18U8K0a_pIVAX6Cb4zy08XkdGoGGWtS70/view?usp=sharing
This video is about the bug.

**Comment by PaulBGD** [comment]
Yikes, taking a look at now.

**Comment by PaulBGD** [comment]
Fixed in https://github.com/TECHNOVE/Airplane/commit/08b29b153ade3d59f6bde7e5ad23b2d6e34ba06b
