### ISSUE TITLE
Swimming Bug

### ISSUE THREAD

**Issue by Pantera07** [Technove/AirplaneLite#61]
https://drive.google.com/file/d/1KBnfPpFUH9Zw7yovWrw9-993gWfKUTsO/view?usp=sharing
In situations such as video, it is impossible to move while swimming.

**Comment by Pantera07** [comment]
https://drive.google.com/file/d/1uV2Km6Y3FDeS5EG8y13MUU9wnZB4zppo/view?usp=sharing
Another similar bug video.

**Comment by Pantera07** [comment]
https://drive.google.com/file/d/15PN5EqfL41VCdBmzk7hNSl6SBaU81KxE/view?usp=sharing
Camera shakes up and down while swimming

**Comment by PaulBGD** [comment]
https://github.com/TECHNOVE/Airplane/commit/a74424ab0212a924c7ef921bfb7ec143c874cba4
https://ci.tivy.ca/job/Airplane-1.17/86/

Can you test if this fixes it? Thank you so much for these reports with the videos!

**Comment by Pantera07** [comment]
This bug has been fixed.
