### ISSUE TITLE
TNT spawned in wrong position after Airplane-Purpur-1.17 build 45

### ISSUE THREAD

**Issue by KujouMolean** [Technove/AirplaneLite#64]
# Description
here's build 44
![before](https://user-images.githubusercontent.com/54140989/135788801-e8493912-3adf-4091-8000-e967b4a0ee9d.gif)

here's build 45

![after](https://user-images.githubusercontent.com/54140989/135788820-00d1bd9e-bcf2-49bd-95f9-2a2a3c9a8dd1.gif)

Easy to found that tnt spawnd in wrong location

# Environment

the building (litematic file , need unzip):
[test.litematic.zip](https://github.com/TECHNOVE/Airplane/files/7275305/test.litematic.zip)

all config(include airplane.yml,bukkit.yml,paper.yml,purpur.yml,spigot.yml):

[airplane&bukkit&paper&purpur&spigot.zip](https://github.com/TECHNOVE/Airplane/files/7275311/airplane.bukkit.paper.purpur.spigot.zip)

**Comment by PaulBGD** [comment]
This is likely an upstream change with Paper, can you figure out what version it occurs on there?

**Comment by KujouMolean** [comment]
> This is likely an upstream change with Paper, can you figure out what version it occurs on there?

No problem with latest Paper build. And I tried several Paper builds around Airplane-Purpur-1.17#45, no problem yet.

**Comment by PaulBGD** [comment]
Alright, I'll take a look at this.

**Comment by PaulBGD** [comment]
Fixed this a while ago, feel free to reopen if it happens again.
