### ISSUE TITLE
(PacketPlayInDifficultyChange) Error

### ISSUE THREAD

**Issue by EvaRaud** [Technove/AirplaneLite#65]
Hello guys
Some players on our server can't join after moving to new hosting

In console;
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/2 (PacketPlayInDifficultyChange) was larger than I expected, found 4 bytes extra whilst reading packet 2

We see in chat that he joins but server kicks him in 1 second.

80% off all players can join easily from 1st attempt
But other 20% nope

They see that on their screen
![image](https://user-images.githubusercontent.com/92093142/136375462-9b7a66f4-c599-4a0e-85a7-d567acf96356.png)

Server running on minecraft version 1.17.1
Linux
Difficulty Hard
Patched_1.17.1.jar:git-Airplane-49

**Comment by PaulBGD** [comment]
This is a plugin or a proxy issue.
