### ISSUE TITLE
Bugged GUIs

### ISSUE THREAD

**Issue by FrancyMak** [Technove/AirplaneLite#71]
Hi, since I updated to 1.17 I have been experiencing the following problem in all plugins using custom gui.

The problem is that when you click the items in them, it creates a kind of visual bug that takes the item from your GUI. The thing is that with the update to 1.17, the problem has increased fivefold and practically every time you click on a GUI there is this problem.

https://streamable.com/nz5hvp

**Comment by PaulBGD** [comment]
This is a common issue upstream, unfortunately we can't fix it here in Airplane.
