### ISSUE TITLE
1.18 

### ISSUE THREAD

**Issue by lilyprism** [Technove/AirplaneLite#75]
When is Airplane going to start working on 1.18 support?

**Comment by ghost** [comment]
Probably, never. Check this message in the Airplane's Discord server: https://discord.com/channels/748023548467216394/753780217117671545/912421001189531758.

**Comment by MrPowerGamerBR** [comment]
> Probably, never. Check this message in the Airplane's Discord server: https://discord.com/channels/748023548467216394/753780217117671545/912421001189531758.

For people too lazy to join Airplane's Discord server:

![image](https://user-images.githubusercontent.com/9496359/144452839-c2a38966-9c3b-4215-b843-ecbcbc6969fe.png)
